version: '3.8'
services:
  server:
    build: ./server
    working_dir: /server
    environment:
      DB_URI: mongodb://db:27017/dev
      DB_USER: ramy
      DB_PASS: 123456
      JWT_SECRET: Empty
    ports:
      - '4000:4000'
    networks:
      - 'mern-app'
    volumes:
      - ./server:/server
      - /server/node_modules/
    depends_on:
      - 'redis'
  db:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ramy
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - 'mern-app'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - 'mern-app'
    command: ['redis-server']
networks:
  mern-app:
    driver: bridge
