export const usersMutations = {
  INCREASE_PAGENUM: 'INCREASE_PAGENUM',
  SET_HAS_MORE: 'SET_HAS_MORE',
  PUSH_TO_USERS: 'PUSH_TO_USERS',
  REMOVE_FROM_USERS: 'REMOVE_FROM_USERS',
  RESET_USERS: 'RESET_USERS',
}
