export const authMutations = {
  LOGIN: 'LOGIN',
  SET_LOADING: 'SET_LOADING',
  LOGGED_OUT: 'LOGGED_OUT',
  PUSH_FRIEND_REQUEST: 'PUSH_FRIEND_REQUEST',
  REMOVE_FRIEND_REQUEST: 'REMOVE_FRIEND_REQUEST',
  ADD_FRIEND: 'ADD_FRIEND',
}
